const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');const {WindowsDriveState}=require('../src/windows-drive-state');const {WindowsFolderMoveJournal}=require('../src/windows-drive-folder-move-journal');const {finishFolderRebindings}=require('../src/windows-drive-folder-move');
async function fixture(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'ember-folder-finish-'));await fs.mkdir(path.join(root,'New'));const file=path.join(root,'New','file');await fs.writeFile(file,'Data');const hash=crypto.createHash('sha256').update('Data').digest('hex'),state=new WindowsDriveState({directory:path.join(root,'state'),safeStorage:{isEncryptionAvailable:()=>true,encryptString:value=>Buffer.from(value),decryptString:value=>value.toString()}});await state.load();const previous={key:'remote/Old/file',size:4,etag:'old',fileID:'v1'},copy={key:'remote/New/file',size:4,etag:'new',fileID:'v2',hash};await state.update(value=>{value.materialized={Old:{key:'remote/Old/'},'Old/file':previous};});const journal=new WindowsFolderMoveJournal(state),id=await journal.begin({from:'Old',local:'New',key:'remote/New/',objects:[{name:previous.key,...previous}],fingerprints:{'Old/file':{hash,size:4,pinState:1}}});await journal.copied(id,copy.key,copy);await journal.readyToDelete(id);await journal.deleting(id,previous.key);await journal.deleted(id,previous.key);await journal.readyToAcknowledge(id);const identities={New:JSON.stringify({key:'remote/Old/'}),'New/file':JSON.stringify(previous)},events=[];const bridge={lockFolder:async local=>({token:local,identity:identities[local]}),unlockFolder:async()=>{},lockUpload:async local=>({token:local,localPath:file,cloud:true,modifiedBytes:0,size:4,pinState:1,identity:identities[local]}),unlockUpload:async()=>{},inspect:async local=>({cloud:true,directory:local==='New',inSync:true,modifiedBytes:0,pinState:1,onDiskBytes:4,identity:identities[local]}),ackMove:async(token,destination)=>{events.push('file');identities[token]=JSON.stringify({key:destination.name,etag:destination.etag,fileID:destination.fileID});},ackFolderMove:async(token,key)=>{events.push('folder');identities[token]=JSON.stringify({key});}};const store={stat:async key=>key===copy.key?{name:key,...copy}:null,read:async()=>Buffer.from('Data')};return {root,file,state,id,journal,bridge,store,events,args:{id,state,bridge,store},close:()=>fs.rm(root,{recursive:true,force:true})};}
test('folder finalization verifies native file and directory identities before committing bindings',async()=>{const f=await fixture();try{assert.equal((await finishFolderRebindings(f.args)).resolved,true);assert.deepEqual(f.events,['file','folder']);assert.equal(f.state.snapshot().materialized['New/file'].etag,'new');assert.deepEqual(f.state.snapshot().folderMoves,{});assert.equal(await fs.readFile(f.file,'utf8'),'Data');}finally{await f.close();}});
test('a lost folder-child acknowledgement is checked read-only without repeating the native write',async()=>{const f=await fixture();try{const original=f.bridge.ackMove;f.bridge.ackMove=async(...args)=>{await original(...args);throw Error('Lost acknowledgement');};await assert.rejects(finishFolderRebindings(f.args),/Lost/);assert.equal(f.state.snapshot().folderMoves[f.id].acknowledging,'New/file');f.bridge.ackMove=original;assert.equal((await finishFolderRebindings(f.args)).resolved,true);assert.deepEqual(f.events,['file','folder']);}finally{await f.close();}});
test('changed local bytes preserve folder journals and prevent native rebinding',async()=>{const f=await fixture();try{await fs.writeFile(f.file,'Edit');await assert.rejects(finishFolderRebindings(f.args),/bytes changed/);assert.deepEqual(f.events,[]);assert(f.state.snapshot().folderMoves[f.id]);assert.equal(await fs.readFile(f.file,'utf8'),'Edit');}finally{await f.close();}});
test('folder recovery needs explicit boolean finishing before deleting an existing cloud source',async()=>{const {recoverFolderMove}=require('../src/windows-drive-folder-move'),f=await fixture();try{await f.state.update(state=>{state.folderMoves[f.id].phase='copied';state.folderMoves[f.id].deleted={};});const destination=f.store.stat;let exists=true,writes=0;f.store.stat=async key=>key==='remote/Old/file'&&exists?{etag:'old',fileID:'v1',size:4}:destination(key);f.store.deleteVersion=async()=>{writes++;exists=false;};for(const finish of [false,'true']){assert.equal((await recoverFolderMove({...f.args,finish})).reason,'folder-source-still-present');assert.equal(writes,0);assert.deepEqual(f.events,[]);}assert.equal((await recoverFolderMove({...f.args,finish:true})).resolved,true);assert.equal(writes,1);assert.equal(f.state.snapshot().materialized['New/file'].etag,'new');}finally{await f.close();}});
test('folder recovery confirms a lost deletion response without deleting twice',async()=>{const {recoverFolderMove}=require('../src/windows-drive-folder-move'),f=await fixture();try{await f.state.update(state=>{state.folderMoves[f.id].phase='copied';state.folderMoves[f.id].deleted={};});const destination=f.store.stat;let exists=true,writes=0;f.store.stat=async key=>key==='remote/Old/file'&&exists?{etag:'old',fileID:'v1',size:4}:destination(key);f.store.deleteVersion=async()=>{writes++;exists=false;throw Error('Lost deletion');};await assert.rejects(recoverFolderMove({...f.args,finish:true}),/Lost deletion/);assert.equal(f.state.snapshot().folderMoves[f.id].deleting,'remote/Old/file');assert.equal((await recoverFolderMove(f.args)).resolved,true);assert.equal(writes,1);assert.deepEqual(f.events,['file','folder']);}finally{await f.close();}});
async function executionFixture(){const f=await fixture();await f.state.update(state=>{state.folderMoves={};});await fs.rename(path.join(f.root,'New'),path.join(f.root,'Old'));await fs.rename(path.join(f.root,'Old'),path.join(f.root,'New'));const inspect=f.bridge.inspect;f.bridge.inspect=async local=>local==='Old'?{exists:false}:{exists:true,...await inspect(local)};const objects=new Map([['remote/Old/file',{name:'remote/Old/file',etag:'old',fileID:'v1',size:4,modified:0}]]);let copies=0,deletions=0;f.store.listAll=async()=>[...objects.values()];f.store.stat=async key=>objects.get(key)||null;f.store.copy=async(source,key)=>{copies++;objects.set(key,{name:key,etag:'new',fileID:'v2',size:source.size,modified:0});return {CopyObjectResult:{ETag:'new'},VersionId:'v2'};};f.store.deleteVersion=async key=>{deletions++;objects.delete(key);};return {...f,objects,count:()=>({copies,deletions}),execute:{root:f.root,from:'Old',local:'New',key:'remote/New/',state:f.state,bridge:f.bridge,store:f.store}};}
test('a real local directory rename completes copies deletions and native rebindings in one transaction',async()=>{const {moveLocalFolder}=require('../src/windows-drive-folder-move'),f=await executionFixture();try{assert.equal((await moveLocalFolder(f.execute)).resolved,true);assert.deepEqual(f.count(),{copies:1,deletions:1});assert.equal(f.objects.has('remote/Old/file'),false);assert.equal(f.objects.get('remote/New/file').etag,'new');assert.deepEqual(f.events,['file','folder']);assert.equal(f.state.snapshot().materialized['New/file'].key,'remote/New/file');assert.equal(await fs.readFile(f.file,'utf8'),'Data');}finally{await f.close();}});
test('a lost folder copy response leaves its intent and recovery never recopies verified bytes',async()=>{const {moveLocalFolder,recoverFolderMove}=require('../src/windows-drive-folder-move'),f=await executionFixture();try{const copy=f.store.copy;f.store.copy=async(...args)=>{await copy(...args);throw Error('Lost copy');};await assert.rejects(moveLocalFolder(f.execute),/Lost copy/);const id=Object.keys(f.state.snapshot().folderMoves)[0];assert(id);assert.deepEqual(f.count(),{copies:1,deletions:0});assert.equal((await recoverFolderMove({...f.execute,id})).reason,'folder-source-still-present');assert.deepEqual(f.count(),{copies:1,deletions:0});assert.equal((await recoverFolderMove({...f.execute,id,finish:true})).resolved,true);assert.deepEqual(f.count(),{copies:1,deletions:1});assert.equal(await fs.readFile(f.file,'utf8'),'Data');}finally{await f.close();}});
test('the complete folder transaction moves explicit zero-byte directory objects with its files',async()=>{const {moveLocalFolder}=require('../src/windows-drive-folder-move'),f=await executionFixture();try{f.objects.set('remote/Old/',{name:'remote/Old/',kind:'folder',size:0,etag:'folder-object',fileID:'folder-v1',modified:0});assert.equal((await moveLocalFolder(f.execute)).resolved,true);assert.deepEqual(f.count(),{copies:2,deletions:2});assert.equal(f.objects.has('remote/Old/'),false);assert.equal(f.objects.has('remote/Old/file'),false);assert.equal(f.objects.get('remote/New/').size,0);assert.equal(await fs.readFile(f.file,'utf8'),'Data');assert.deepEqual(f.state.snapshot().folderMoves,{});}finally{await f.close();}});
async function caseExecutionFixture(){
 const f=await executionFixture();await fs.rename(path.join(f.root,'New'),path.join(f.root,'OLD'));f.file=path.join(f.root,'OLD','file');const identities={OLD:JSON.stringify({key:'remote/Old/'}),'OLD/file':JSON.stringify({key:'remote/Old/file',etag:'old',fileID:'v1'})};
 await f.state.update(state=>{state.mappings={'remote/':{'folder:Old':'Old'},'remote/Old/':{'file:file':'file'}};});
 f.bridge.lockFolder=async local=>({token:local,identity:identities[local]});f.bridge.lockUpload=async local=>({token:local,localPath:f.file,cloud:true,modifiedBytes:0,size:4,pinState:1,identity:identities[local]});f.bridge.inspect=async local=>({exists:true,cloud:true,directory:local==='Old'||local==='OLD',inSync:true,modifiedBytes:0,pinState:1,onDiskBytes:4,identity:identities[local]||identities.OLD});
 f.bridge.ackMove=async(token,object)=>{f.events.push('file');identities[token]=JSON.stringify({key:object.name,etag:object.etag,fileID:object.fileID});};f.bridge.ackFolderMove=async(token,key)=>{f.events.push('folder');identities[token]=JSON.stringify({key});};f.execute={...f.execute,local:'OLD',key:'remote/OLD/'};return f;
}
test('a capitalization-only directory transaction transfers parent mappings and every child identity',async()=>{
 const {moveLocalFolder}=require('../src/windows-drive-folder-move'),f=await caseExecutionFixture();
 try{assert.equal(await f.state.reserveLocalFolderMove('Old','OLD'),'remote/OLD/');assert.equal(f.state.snapshot().materialized.Old.key,'remote/Old/');assert.equal((await moveLocalFolder(f.execute)).resolved,true);const snapshot=f.state.snapshot();assert.equal(snapshot.materialized.OLD.key,'remote/OLD/');assert.equal(snapshot.materialized['OLD/file'].key,'remote/OLD/file');assert.equal(snapshot.materialized.Old,undefined);assert.equal(snapshot.mappings['remote/']['folder:OLD'],'OLD');assert.equal(snapshot.mappings['remote/']['folder:Old'],undefined);assert.equal(snapshot.mappings['remote/OLD/']['file:file'],'file');assert.deepEqual(snapshot.folderMoves,{});assert.equal(await fs.readFile(f.file,'utf8'),'Data');assert.deepEqual(f.count(),{copies:1,deletions:1});}finally{await f.close();}
});
test('a held case-only folder copy can finish while the old Windows path still resolves as an alias',async()=>{
 const {moveLocalFolder,recoverFolderMove}=require('../src/windows-drive-folder-move'),f=await caseExecutionFixture();
 try{const copy=f.store.copy;f.store.copy=async(...args)=>{await copy(...args);throw Error('Lost case copy');};await assert.rejects(moveLocalFolder(f.execute),/Lost case copy/);const id=Object.keys(f.state.snapshot().folderMoves)[0];assert.equal((await recoverFolderMove({...f.execute,id})).reason,'folder-source-still-present');assert.equal((await recoverFolderMove({...f.execute,id,finish:true})).resolved,true);assert.deepEqual(f.count(),{copies:1,deletions:1});assert.equal(await fs.readFile(f.file,'utf8'),'Data');}finally{await f.close();}
});
