const test=require('node:test');const assert=require('node:assert/strict');const {planFolderMove}=require('../src/windows-drive-folder-move-plan');
function fixture(){return {from:'Old folder',local:'New folder',key:'remote/New/',materialized:{'Old folder':{key:'remote/Old/'},'Old folder/Cafe.txt':{key:'remote/Old/Café.txt',etag:'old',fileID:'version',size:4}},objects:[{name:'remote/Old/Café.txt',etag:'old',fileID:'version',size:4},{name:'remote/Old/Empty/.ghost-keep',etag:'empty',size:0}]};}
test('folder preflight preserves local mapped names and exact cloud revision identities',()=>{const input=fixture(),before=structuredClone(input),plan=planFolderMove(input);assert.deepEqual(input,before);assert.equal(plan.placeholders[1].local,'New folder/Cafe.txt');assert.equal(plan.placeholders[1].key,'remote/New/Café.txt');assert.equal(plan.copies[1].key,'remote/New/Empty/.ghost-keep');assert.equal(plan.copies[0].source.fileID,'version');});
test('folder preflight refuses occupied destinations and unfinished ancestor or child operations',()=>{for(const mutate of [f=>f.materialized['new FOLDER/file']={key:'other'},f=>f.objects.push({name:'remote/New/occupied',etag:'x',size:0}),f=>f.pending=[{local:'Old folder/Cafe.txt',key:'other'}],f=>f.pending=[{local:'New folder',key:'other'}]]){const f=fixture();mutate(f);assert.throws(()=>planFolderMove(f),/occupied|unfinished/);}});
test('folder preflight refuses stale, missing and unmaterialized source revisions',()=>{for(const mutate of [f=>f.objects[0].etag='changed',f=>f.objects[0].size=5,f=>f.objects.shift(),f=>f.objects.push({name:'remote/Old/new.txt',etag:'new',size:1})]){const f=fixture();mutate(f);assert.throws(()=>planFolderMove(f),/changed|missing|unmaterialized/);}});
test('folder preflight refuses recursive moves and mismatched child bindings',()=>{for(const mutate of [f=>f.local='Old folder/Nested',f=>f.key='remote/Old/Nested/',f=>f.materialized['Old folder/Cafe.txt'].key='other/file',f=>f.local='../escape']){const f=fixture();mutate(f);assert.throws(()=>planFolderMove(f),/separate|destination|binding|path/);}});
test('folder preflight refuses duplicate aliases and unconfirmed source directory bindings',()=>{for(const mutate of [f=>f.materialized['Old folder/Alias.txt']={...f.materialized['Old folder/Cafe.txt']},f=>f.materialized['Old folder'].remoteConfirmed=false]){const f=fixture();mutate(f);assert.throws(()=>planFolderMove(f),/ambiguous|binding/);}});
test('explicit zero-byte cloud directory objects are copied with their recorded revision',()=>{const f=fixture();f.objects.push({name:'remote/Old/',kind:'folder',size:0,etag:'directory-object'});const plan=planFolderMove(f);assert.equal(plan.copies.at(-1).key,'remote/New/');assert.equal(plan.copies.at(-1).source.etag,'directory-object');f.objects.at(-1).size=1;assert.throws(()=>planFolderMove(f),/unexpected bytes/);});
test('a case-only folder move preserves child suffixes and refuses a competing alias',()=>{
 const f=fixture();f.local='OLD FOLDER';f.key='remote/OLD/';const plan=planFolderMove(f);assert.equal(plan.placeholders[1].local,'OLD FOLDER/Cafe.txt');assert.equal(plan.copies[0].key,'remote/OLD/Café.txt');f.materialized['old folder/other']={key:'other'};assert.throws(()=>planFolderMove(f),/occupied/);
});
