const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');const crypto=require('node:crypto');const {stageRevision}=require('../src/windows-drive-staging');
async function fixture(size=8*1024*1024+123){const root=await fs.mkdtemp(path.join(os.tmpdir(),'ember-pinned-revision-')),driveRoot=path.join(root,'Drive'),directory=path.join(root,'staging');await fs.mkdir(driveRoot);await fs.mkdir(directory);await fs.writeFile(path.join(driveRoot,'pinned.txt'),'Original offline bytes');const data=Buffer.alloc(size,89),object={name:'remote/pinned.txt',etag:'"confirmed"',fileID:'version',size,modified:123},reads=[];
 const store={async read(key,offset,length,version,signal,etag){reads.push({key,offset,length,version,etag});return data.subarray(offset,offset+length);},async stat(){return object;}};return {root,data,reads,object,store,directory,driveRoot,async close(){await fs.rm(root,{recursive:true,force:true});}};}
test('confirmed revisions stage complete durable bytes in bounded version-specific ranges outside the Drive',async()=>{
 for(const size of [0,8*1024*1024+123]){const f=await fixture(size);try{const staged=await stageRevision(f);assert.deepEqual(await fs.readFile(staged.file),f.data);assert.equal(staged.hash,crypto.createHash('sha256').update(f.data).digest('hex'));assert.equal(staged.size,size);assert.equal(f.reads.length,size?2:0);for(const read of f.reads){assert.equal(read.version,'version');assert.equal(read.etag,'"confirmed"');assert.ok(read.length<=8*1024*1024);}assert.equal(await fs.readFile(path.join(f.driveRoot,'pinned.txt'),'utf8'),'Original offline bytes');await staged.cleanup();assert.deepEqual(await fs.readdir(f.directory),[]);}finally{await f.close();}}
});
test('failed or cancelled staging removes only its partial download and preserves pinned bytes',async()=>{
 for(const fault of ['short','missing','etag','version','size','cancelled']){const f=await fixture(4);try{let signal;if(fault==='short')f.store.read=async()=>Buffer.alloc(3);else if(fault==='cancelled'){const controller=new AbortController();signal=controller.signal;const read=f.store.read;f.store.read=async(...args)=>{const bytes=await read(...args);controller.abort();return bytes;};}else f.store.stat=async()=>fault==='missing'?null:{...f.object,...({etag:{etag:'"new"'},version:{fileID:'new'},size:{size:5}}[fault])};await assert.rejects(stageRevision({...f,signal}));assert.deepEqual(await fs.readdir(f.directory),[]);assert.equal(await fs.readFile(path.join(f.driveRoot,'pinned.txt'),'utf8'),'Original offline bytes');}finally{await f.close();}}
});
test('staging refuses directories inside the Drive before creating a revision file',async()=>{
 const f=await fixture(4);try{for(const directory of [f.driveRoot,path.join(f.driveRoot,'new','staging')])await assert.rejects(stageRevision({...f,directory}),/outside/);assert.deepEqual(await fs.readdir(f.driveRoot),['pinned.txt']);assert.equal(f.reads.length,0);}finally{await f.close();}
});
