const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');const {WindowsDriveState}=require('../src/windows-drive-state');const {WindowsPinnedUpdateJournal}=require('../src/windows-drive-pinned-journal');const {stageRevision}=require('../src/windows-drive-staging');const {capturePinnedRevision}=require('../src/windows-drive-pinned-backup');const {pendingOperations,operationTouches}=require('../src/windows-drive-pending');
async function fixture(){const directory=await fs.mkdtemp(path.join(os.tmpdir(),'ember-pinned-journal-')),driveRoot=path.join(directory,'Drive');await fs.mkdir(driveRoot);const localPath=path.join(driveRoot,'pinned.txt');await fs.writeFile(localPath,'Data');const key=crypto.randomBytes(32),safeStorage={isEncryptionAvailable:()=>true,encryptString(text){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),bytes=Buffer.concat([cipher.update(text),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),bytes]);},decryptString(bytes){const cipher=crypto.createDecipheriv('aes-256-gcm',key,bytes.subarray(0,12));cipher.setAuthTag(bytes.subarray(12,28));return Buffer.concat([cipher.update(bytes.subarray(28)),cipher.final()]).toString();}};
 const state=new WindowsDriveState({directory:path.join(directory,'profile'),safeStorage});await state.load();const previous={key:'remote/pinned.txt',etag:'"old"',fileID:'old-version',size:4,modified:1};await state.markMaterialized('pinned.txt',previous);const object={name:previous.key,etag:'"new"',fileID:'new-version',size:4,modified:2},store={read:async()=>Buffer.from('Next'),stat:async()=>object};const staged=await stageRevision({directory:path.join(directory,'staging'),driveRoot,store,object}),journal=new WindowsPinnedUpdateJournal(state);
 const backup=await capturePinnedRevision({lock:{token:'native',cloud:true,inSync:true,pinState:1,modifiedBytes:0,size:4,localPath},directory:staged.directory,driveRoot});
 return {directory,driveRoot,state,journal,previous,staged,backup,args:{local:'pinned.txt',previous,staged},async reopen(){const reopened=new WindowsDriveState({directory:state.directory,safeStorage});await reopened.load();return reopened;},async close(){await fs.rm(directory,{recursive:true,force:true});}};
}
test('pinned update and both staged revision proofs persist encrypted across restart until verified completion',async()=>{
 const f=await fixture();try{const id=await f.journal.begin(f.args);await f.journal.recordBackup(id,f.backup);const reopened=await f.reopen(),journal=new WindowsPinnedUpdateJournal(reopened);assert.equal(reopened.snapshot().pinnedUpdates[id].phase,'backedUp');assert(!(await fs.readFile(reopened.file)).includes(Buffer.from(f.staged.file)));await journal.replacing(id);await journal.installed(id,{hash:f.staged.hash,size:4});await journal.complete(id,f.staged.identity,f.staged.hash);assert.deepEqual((await f.reopen()).snapshot().pinnedUpdates,{});assert.equal(reopened.snapshot().materialized['pinned.txt'].etag,'"new"');assert.equal(await fs.readFile(f.backup.file,'utf8'),'Data');assert.equal(await fs.readFile(f.staged.file,'utf8'),'Next');}finally{await f.close();}
});
test('replacement cannot start without a durable matching offline backup or clear a wrong installation proof',async()=>{
 const f=await fixture();try{const id=await f.journal.begin(f.args);await assert.rejects(f.journal.replacing(id),/durable offline backup/);await assert.rejects(f.journal.recordBackup(id,{...f.backup,size:5}),/backup proof/);assert.equal(f.state.snapshot().pinnedUpdates[id].phase,'prepared');await f.journal.recordBackup(id,f.backup);await f.journal.replacing(id);await assert.rejects(f.journal.installed(id,{hash:'0'.repeat(64),size:4}),/installation proof/);await assert.rejects(f.journal.complete(id,f.staged.identity,f.staged.hash),/completion proof/);assert.equal(f.state.snapshot().pinnedUpdates[id].phase,'replacing');assert.equal(f.state.snapshot().materialized['pinned.txt'].etag,'"old"');}finally{await f.close();}
});
test('held pinned updates protect cache, namespace, uploads and moves without replay',async()=>{
 const f=await fixture();try{await f.journal.begin(f.args);assert.equal(pendingOperations(f.state.snapshot()).some(entry=>operationTouches(entry,'PINNED.TXT',f.previous.key)),true);await assert.rejects(f.journal.begin(f.args),/unfinished operation/);await assert.rejects(f.state.beginUpload({local:'pinned.txt',key:f.previous.key,size:4,modified:1,hash:f.backup.hash,previous:f.previous}),/pinned update/);await assert.rejects(f.state.beginMove({from:'pinned.txt',local:'renamed.txt',key:'remote/renamed.txt',previous:f.previous,size:4,modified:1,hash:f.backup.hash}),/unfinished operation/);assert.equal(Object.keys(f.state.snapshot().pinnedUpdates).length,1);}finally{await f.close();}
});
test('recovered completion requires the recorded new revision and preserves changed materialized bindings',async()=>{
 for(const fault of ['hash','revision','source']){const f=await fixture();try{const id=await f.journal.begin(f.args);await f.journal.recordBackup(id,f.backup);await f.journal.replacing(id);if(fault==='source')await f.state.markMaterialized('pinned.txt',{...f.previous,etag:'"replacement"'});await assert.rejects(f.journal.resolveRecovered(id,fault==='revision'?{...f.staged.identity,fileID:'other-version'}:f.staged.identity,fault==='hash'?'0'.repeat(64):f.staged.hash),/completion proof/);assert.equal(f.state.snapshot().pinnedUpdates[id].phase,'replacing');assert.equal(await fs.readFile(f.backup.file,'utf8'),'Data');}finally{await f.close();}}
});
test('recovery can atomically finish a verified installation whose final acknowledgement was lost',async()=>{
 const f=await fixture();try{const id=await f.journal.begin(f.args);await f.journal.recordBackup(id,f.backup);await f.journal.replacing(id);const reopened=await f.reopen();await new WindowsPinnedUpdateJournal(reopened).resolveRecovered(id,f.staged.identity,f.staged.hash);assert.deepEqual((await f.reopen()).snapshot().pinnedUpdates,{});assert.equal(reopened.snapshot().materialized['pinned.txt'].fileID,'new-version');}finally{await f.close();}
});
