const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');
const {WindowsDriveState}=require('../src/windows-drive-state');const {WindowsFolderMoveJournal}=require('../src/windows-drive-folder-move-journal');const {pendingOperations,operationTouches}=require('../src/windows-drive-pending');
const hash=crypto.createHash('sha256').update('Data').digest('hex');
async function fixture(){const directory=await fs.mkdtemp(path.join(os.tmpdir(),'ember-folder-journal-')),safeStorage={isEncryptionAvailable:()=>true,encryptString:value=>Buffer.from(value),decryptString:value=>value.toString()},state=new WindowsDriveState({directory,safeStorage});await state.load();const previous={key:'remote/Old/file',size:4,etag:'old',fileID:'v1'};await state.update(value=>{value.materialized={'Old':{key:'remote/Old/'},'Old/file':previous};});return {state,journal:new WindowsFolderMoveJournal(state),input:{from:'Old',local:'New',key:'remote/New/',objects:[{name:previous.key,...previous}],fingerprints:{'Old/file':{hash,size:4}}},reopen:async()=>{const next=new WindowsDriveState({directory,safeStorage});await next.load();return next;},close:()=>fs.rm(directory,{recursive:true,force:true})};}
test('folder intent survives reload and protects both complete local/cloud subtrees',async()=>{const f=await fixture();try{const id=await f.journal.begin(f.input),reopened=await f.reopen(),entry=reopened.snapshot().folderMoves[id];assert.equal(entry.phase,'prepared');assert.equal(entry.fingerprints['Old/file'].hash,hash);const pending=pendingOperations(reopened.snapshot());for(const [local,key] of [['Old/file','other'],['New/child','other'],['unmapped','remote/Old/file'],['unmapped','remote/New/new']])assert(pending.some(item=>operationTouches(item,local,key)));await assert.rejects(new WindowsFolderMoveJournal(reopened).begin(f.input),/unfinished/);}finally{await f.close();}});
test('folder journal requires every verified copy before durable deletion and preserves original bindings',async()=>{const f=await fixture();try{const id=await f.journal.begin(f.input),original=f.state.snapshot().materialized;await assert.rejects(f.journal.readyToDelete(id),/Every folder copy/);await assert.rejects(f.journal.copied(id,'remote/New/file',{key:'remote/New/file',size:4,etag:'new',hash:'0'.repeat(64)}),/bytes/);await f.journal.copied(id,'remote/New/file',{key:'remote/New/file',size:4,etag:'new',fileID:'v2',hash});await f.journal.readyToDelete(id);await f.journal.deleting(id,'remote/Old/file');const reopened=await f.reopen();assert.equal(reopened.snapshot().folderMoves[id].deleting,'remote/Old/file');const journal=new WindowsFolderMoveJournal(reopened);await assert.rejects(journal.readyToAcknowledge(id),/Every recorded/);await journal.deleted(id,'remote/Old/file');await journal.readyToAcknowledge(id);assert.equal(reopened.snapshot().folderMoves[id].phase,'deleted');assert.deepEqual(reopened.snapshot().materialized,original);}finally{await f.close();}});
test('folder bindings remain original until every native acknowledgement is verified',async()=>{const f=await fixture();try{const id=await f.journal.begin(f.input),copy={key:'remote/New/file',size:4,etag:'new',fileID:'v2',hash};await f.journal.copied(id,copy.key,copy);await f.journal.readyToDelete(id);await f.journal.deleting(id,'remote/Old/file');await f.journal.deleted(id,'remote/Old/file');await f.journal.readyToAcknowledge(id);await assert.rejects(f.journal.complete(id),/Every moved/);await f.journal.acknowledging(id,'New');await f.journal.acknowledged(id,'New',{placeholder:{cloud:true,directory:true,identity:JSON.stringify({key:'remote/New/'})}});await assert.rejects(f.journal.complete(id),/Every moved/);await f.journal.acknowledging(id,'New/file');const proof={hash,size:4,placeholder:{cloud:true,inSync:true,modifiedBytes:0,identity:JSON.stringify(copy)}};await assert.rejects(f.journal.acknowledged(id,'New/file',{...proof,hash:'0'.repeat(64)}),/content/);await f.journal.acknowledged(id,'New/file',proof);await f.journal.complete(id);const reopened=await f.reopen();assert.deepEqual(reopened.snapshot().folderMoves,{});assert.equal(reopened.snapshot().materialized['Old/file'],undefined);assert.equal(reopened.snapshot().materialized['New/file'].etag,'new');assert.equal(reopened.snapshot().materialized['New'].key,'remote/New/');}finally{await f.close();}});
test('reserving a renamed folder persists its mapped destination without rebinding the source tree',async()=>{const f=await fixture();try{await f.state.update(state=>{state.materialized.Parent={key:'remote/',remoteConfirmed:true};state.mappings['remote/']={'folder:New cloud name':'New local name'};});const before=f.state.snapshot().materialized;assert.equal(await f.state.reserveLocalFolderMove('Old','Parent/New local name'),'remote/New cloud name/');const reopened=await f.reopen();assert.deepEqual(reopened.snapshot().materialized,before);assert.equal(reopened.snapshot().materialized['Parent/New local name'],undefined);await assert.rejects(reopened.reserveLocalFolderMove('Old','Missing/New'),/parent folder/);await assert.rejects(reopened.reserveLocalFolderMove('Old','Old/Child'),/separate/);}finally{await f.close();}});
test('held folder trees reject child reservations uploads backups and individual moves atomically',async()=>{
 const f=await fixture();try{await f.journal.begin(f.input);const before=f.state.snapshot();
  for(const operation of [()=>f.state.reserveLocalFile('Old/new'),()=>f.state.reserveLocalFolder('New/new'),()=>f.state.reserveRemoteFile('remote/New/new'),()=>f.state.beginUpload({local:'Old/file',key:'remote/Old/file',size:4,modified:1,hash}),()=>f.state.beginFolderUpload('Old','remote/Old/'),()=>f.state.beginBackup({local:'Other/file',key:'remote/New/file',size:4,hash}),()=>f.state.beginMove({from:'Old/file',local:'Other/file',key:'remote/Other/file',previous:before.materialized['Old/file'],size:4,modified:1,hash})]){await assert.rejects(operation(),/unfinished/i);assert.deepEqual(f.state.snapshot(),before,'A refused competing operation must not change mappings or journals');}
  assert.equal(await f.state.reserveLocalFile('Independent/file'),'Independent/file');
 }finally{await f.close();}
});
test('finalization accepts only identical destination reservations from a held namespace listing',async()=>{
 for(const conflicting of [false,true]){const f=await fixture();try{
  await f.state.update(state=>{state.mappings={'remote/Old/':{'file:file':'file','folder:Empty':'Empty'},'remote/New/':{'file:file':'file'}};});
  const id=await f.journal.begin(f.input),copy={key:'remote/New/file',size:4,etag:'new',fileID:'v2',hash};await f.journal.copied(id,copy.key,copy);await f.journal.readyToDelete(id);await f.journal.deleting(id,'remote/Old/file');await f.journal.deleted(id,'remote/Old/file');await f.journal.readyToAcknowledge(id);
  await f.journal.acknowledging(id,'New');await f.journal.acknowledged(id,'New',{placeholder:{cloud:true,directory:true,identity:JSON.stringify({key:'remote/New/'})}});await f.journal.acknowledging(id,'New/file');await f.journal.acknowledged(id,'New/file',{hash,size:4,placeholder:{cloud:true,inSync:true,modifiedBytes:0,identity:JSON.stringify(copy)}});
  if(conflicting){await f.state.update(state=>{state.mappings['remote/New/']['file:file']='Different';});const before=f.state.snapshot();await assert.rejects(f.journal.complete(id),/mapping is occupied/);assert.deepEqual(f.state.snapshot(),before);}
  else{await f.journal.complete(id);assert.deepEqual(f.state.snapshot().mappings['remote/New/'],{'file:file':'file','folder:Empty':'Empty'});assert.deepEqual(f.state.snapshot().folderMoves,{});}
 }finally{await f.close();}}
});
test('a conflicting destination reservation refuses a folder journal before cloud transfers',async()=>{
 const f=await fixture();try{await f.state.update(state=>{state.mappings={'remote/Old/':{'file:file':'file'},'remote/New/':{'file:file':'Different'}};});const before=f.state.snapshot();await assert.rejects(f.journal.begin(f.input),/mapping is occupied/);assert.deepEqual(f.state.snapshot(),before);}finally{await f.close();}
});
