const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {WindowsDriveState}=require('../src/windows-drive-state');
const {prepareDirectoryDeletion,recoverDirectoryDeletion,completeDirectoryDeletion}=require('../src/windows-drive-directory-delete');
async function fixture(){
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'ember-directory-delete-')),safeStorage={isEncryptionAvailable:()=>true,encryptString:value=>Buffer.from(value),decryptString:value=>value.toString()},state=new WindowsDriveState({directory,safeStorage});await state.load();
 const local='Folder',previous={key:'remote/Folder/',etag:null,fileID:null,size:0};await state.markMaterialized(local,{...previous,remoteConfirmed:true});
 const objects=new Map([[previous.key,{name:previous.key,etag:'directory',fileID:'v1',size:0}], [previous.key+'.ghost-keep',{name:previous.key+'.ghost-keep',etag:'marker',fileID:'v2',size:0}]]);let copies=0,deletes=0,exists=true;
 const store={listAll:async()=>[...objects.values()],stat:async key=>objects.get(key)||null,copy:async(source,key)=>{copies++;objects.set(key,{name:key,etag:'copy-'+copies,fileID:'copy-v'+copies,size:0});return {CopyObjectResult:{ETag:'copy-'+copies},VersionId:'copy-v'+copies};},deleteVersion:async(key,version,{etag})=>{assert.equal(version,'');assert.equal(objects.get(key)?.etag,etag);assert.equal([...objects.keys()].filter(key=>key.startsWith('.ghost-trash/')).length,2,'all directory objects must be copied before any source deletion');deletes++;objects.delete(key);}};
 const bridge={inspect:async()=>({exists})};return {state,local,previous,objects,store,bridge,args:{local,previous,state,store,bridge},counts:()=>({copies,deletes}),removeLocal:()=>{exists=false;},reopen:async()=>{const next=new WindowsDriveState({directory,safeStorage});await next.load();return next;},close:()=>fs.rm(directory,{recursive:true,force:true})};
}
test('empty directory deletion verifies both trash copies before deleting any source and waits for actual local absence',async()=>{
 const f=await fixture();try{const result=await prepareDirectoryDeletion(f.args);assert.equal(result.readyForLocalDeletion,true);assert.deepEqual(f.counts(),{copies:2,deletes:2});const entry=f.state.snapshot().deletes[result.id];assert.equal(entry.directory,true);assert.equal(entry.tree,true);assert.equal(entry.phase,'deleted');assert.equal(f.objects.size,2);assert(f.state.snapshot().materialized.Folder);assert.equal((await completeDirectoryDeletion({...f.args,id:result.id})).resolved,false);f.removeLocal();assert.equal((await completeDirectoryDeletion({...f.args,id:result.id})).resolved,true);assert.deepEqual(f.state.snapshot().deletes,{});assert.equal(f.state.snapshot().materialized.Folder,undefined);}finally{await f.close();}
});
test('a lost directory copy reply survives state reload and read-only checks never copy or delete missing objects',async()=>{
 const f=await fixture();try{const copy=f.store.copy;f.store.copy=async(...args)=>{const result=await copy(...args);if(f.counts().copies===1)throw Error('Lost directory copy');return result;};await assert.rejects(prepareDirectoryDeletion(f.args),/Lost directory copy/);const id=Object.keys(f.state.snapshot().deletes)[0],state=await f.reopen(),args={...f.args,state,id};for(const finish of [false,'true'])assert.equal((await recoverDirectoryDeletion({...args,finish})).reason,'directory-delete-copy-missing');assert.deepEqual(f.counts(),{copies:1,deletes:0});assert.equal((await recoverDirectoryDeletion({...args,finish:true})).readyForLocalDeletion,true);assert.deepEqual(f.counts(),{copies:2,deletes:2});}finally{await f.close();}
});
test('a lost directory delete reply is acknowledged after restart without repeating any confirmed copy or deletion',async()=>{
 const f=await fixture();try{const remove=f.store.deleteVersion;f.store.deleteVersion=async(...args)=>{await remove(...args);if(f.counts().deletes===1)throw Error('Lost directory delete');};await assert.rejects(prepareDirectoryDeletion(f.args),/Lost directory delete/);const id=Object.keys(f.state.snapshot().deletes)[0],state=await f.reopen(),args={...f.args,state,id};assert.equal((await recoverDirectoryDeletion(args)).reason,'directory-delete-source-still-present');assert.deepEqual(f.counts(),{copies:2,deletes:1});assert.equal((await recoverDirectoryDeletion({...args,finish:true})).readyForLocalDeletion,true);assert.deepEqual(f.counts(),{copies:2,deletes:2});}finally{await f.close();}
});
test('new cloud children or changed trash refuse directory completion without removing their bytes',async()=>{
 const f=await fixture();try{const copy=f.store.copy;f.store.copy=async(...args)=>{await copy(...args);throw Error('Hold');};await assert.rejects(prepareDirectoryDeletion(f.args),/Hold/);const id=Object.keys(f.state.snapshot().deletes)[0];f.objects.set('remote/Folder/new.txt',{name:'remote/Folder/new.txt',etag:'new',size:5});await assert.rejects(recoverDirectoryDeletion({...f.args,id,finish:true}),/gained children/);assert.deepEqual(f.counts(),{copies:1,deletes:0});f.objects.delete('remote/Folder/new.txt');const key=f.state.snapshot().deletes[id].copies[0].key;f.objects.get(key).size=5;await assert.rejects(recoverDirectoryDeletion({...f.args,id,finish:true}),/trash revision/);assert.deepEqual(f.counts(),{copies:1,deletes:0});}finally{await f.close();}
});
test('an unfinished directory deletion protects local and cloud children and completion refuses changed bindings',async()=>{
 const f=await fixture();try{const copy=f.store.copy;f.store.copy=async(...args)=>{await copy(...args);throw Error('Hold');};await assert.rejects(prepareDirectoryDeletion(f.args),/Hold/);const snapshot=f.state.snapshot();await assert.rejects(f.state.reserveLocalFile('Folder/new.txt'),/unfinished|protected/i);await assert.rejects(f.state.reserveRemoteFile('remote/Folder/new.txt'),/unfinished|protected/i);assert.deepEqual(f.state.snapshot(),snapshot);f.store.copy=copy;const id=Object.keys(snapshot.deletes)[0];await recoverDirectoryDeletion({...f.args,id,finish:true});f.removeLocal();await f.state.update(data=>{data.materialized.Folder.key='another/';});await assert.rejects(completeDirectoryDeletion({...f.args,id}),/binding or children changed/);assert.ok(f.state.snapshot().deletes[id]);}finally{await f.close();}
});
test('a confirmed inferred empty prefix can be removed without making any cloud writes',async()=>{
 const f=await fixture();try{f.objects.clear();const result=await prepareDirectoryDeletion(f.args);assert.equal(result.readyForLocalDeletion,true);assert.equal(result.readOnlyCloudCheck,true);assert.deepEqual(f.counts(),{copies:0,deletes:0});f.removeLocal();assert.equal((await completeDirectoryDeletion({...f.args,id:result.id})).resolved,true);}finally{await f.close();}
});
test('changing another trash revision during a deletion prevents removing its original directory object',async()=>{
 const f=await fixture();try{const remove=f.store.deleteVersion;f.store.deleteVersion=async(...args)=>{await remove(...args);const entry=Object.values(f.state.snapshot().deletes)[0];f.objects.get(entry.copies[1].key).size=5;};await assert.rejects(prepareDirectoryDeletion(f.args),/trash copy changed/);assert.deepEqual(f.counts(),{copies:2,deletes:1});assert(f.objects.has('remote/Folder/.ghost-keep'));assert(f.state.snapshot().materialized.Folder);}finally{await f.close();}
});
