const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');const {backupPlan}=require('../src/windows-drive-backup-plan');
async function fixture(){const profile=await fs.mkdtemp(path.join(os.tmpdir(),'ember-backup-plan-')),driveRoot=path.join(profile,'Drive'),notesDir=path.join(profile,'Notes');await fs.mkdir(driveRoot);await fs.mkdir(notesDir);return {profile,driveRoot,notesDir,async settings(value){await fs.writeFile(path.join(profile,'settings.json'),JSON.stringify(value));},async close(){await fs.rm(profile,{recursive:true,force:true});}};}
test('backup planner follows persisted opt-in and discovers new notes after the app exits',async()=>{
 const f=await fixture();try{await fs.writeFile(path.join(f.notesDir,'one.md'),'First');assert.deepEqual(await backupPlan(f),[]);await f.settings({driveBackupNotes:true,notesDir:f.notesDir});assert.equal((await backupPlan(f))[0].relative,'Notes/one.md');await fs.mkdir(path.join(f.notesDir,'nested'));await fs.writeFile(path.join(f.notesDir,'nested','two.md'),'New');await fs.writeFile(path.join(f.notesDir,'.private.md'),'Hidden');assert.deepEqual((await backupPlan(f)).map(j=>j.relative).sort(),['Notes/nested/two.md','Notes/one.md']);await f.settings({driveBackupNotes:false,notesDir:f.notesDir});assert.deepEqual(await backupPlan(f),[]);}finally{await f.close();}
});
test('recording backups choose completed plain and edited media and generate matching notes without changing the library',async()=>{
 const f=await fixture();try{const id='20261007-120000',library=path.join(f.profile,'recordings'),folder=path.join(library,id);await fs.mkdir(folder,{recursive:true});for(const name of ['recording.mp4','finished.mp4','edited.mp4'])await fs.writeFile(path.join(folder,name),name);await f.settings({driveBackupRecordings:true});const item={title:'Call: notes',createdAt:'2026-10-07T12:00:00Z',status:'done',finished:true,edited:{auto:false},summary:'Summary',transcript:[{text:'Hello'}],chapters:[{title:'Start'}]};await fs.writeFile(path.join(library,'recordings.json'),JSON.stringify({recordings:{[id]:item}}));const jobs=await backupPlan(f);assert.equal(jobs.length,3);assert.equal(path.basename(jobs[0].file),'finished.mp4');assert.equal(jobs[1].relative,'Recordings/2026-10-07 Call- notes/Call- notes (edited).mp4');assert.equal(jobs[2].text,'# Call: notes\n\nSummary\n\n- Start\n\nHello');assert.equal(await fs.readFile(path.join(folder,'recording.mp4'),'utf8'),'recording.mp4');item.status='recording';await fs.writeFile(path.join(library,'recordings.json'),JSON.stringify({recordings:{[id]:item}}));assert.deepEqual(await backupPlan(f),[]);}finally{await f.close();}
});
test('backup planning refuses recursive Drive sources and respects cancellation',async()=>{
 const f=await fixture();try{await f.settings({driveBackupNotes:true,notesDir:f.driveRoot});await assert.rejects(backupPlan(f),/cannot be inside Drive/);const controller=new AbortController();controller.abort();await f.settings({});await assert.rejects(backupPlan({...f,signal:controller.signal}),/cancelled/);}finally{await f.close();}
});
